### ISSUE TITLE
How do I start up the project?

### ISSUE THREAD

**Issue by dzgreen** [tkjone/wagtail-starter-kit#4]
Hi 

Thanks for settings this up. How do I start up the project after running the cookiecutter successfully? 

Best,
Dominik

**Comment by tkjone** [comment]
Hey there @dzgreen,

After you run the cookiecutter you will have a new base project complete with a README.rst file that outlines how to setup the project.  Here is a link to the README.rst  https://github.com/tkjone/wagtail-starter-kit/tree/master/%7B%7Bcookiecutter.repo_name%7D%7D

Sorry for the late response and I hope this helps!
